markdown: kramdown

exclude:
  - package.json
  - node_modules
  - gulpfile.js

# Dependencies
highlighter:      rouge

gems:
  - jekyll-paginate

timezone: Asia/Shanghai

# Setup
title:            'Shang Wen Long'
name:             'Shang Wen Long'
description:      'Programmer'
baseurl:              

# Assets
images:         '/images'
pdfs:           '/pdf'

author:
  name:           'Shang Wen Long'
  url:            'https://dxcqcv.github.io'
  email:          'dxcqcv@gmail.com'
  github:         'https://github.com/dxcqcv'
  facebook:       'https://www.facebook.com/shang.roy'
  twitter:        'https://twitter.com/dxcqcv'
  googleplus:     ''
  linkedin:       ''

paginate:         3
paginate_path:    "/blog/page:num/"

# Custom vars
version:          1.0.0

github:
  repo:          'https://github.com/dxcqcv/dxcqcv.github.io' 

